source 'https://rubygems.org'

gem 'rails', '3.2.8'

gem 'sqlite3'


group :assets do

  gem 'coffee-rails', '3.2.1'
  gem "compass-rails", "1.0.3"


  gem 'sass-rails', '3.2.3'
  gem "haml-rails", "0.3.5"

  gem 'therubyracer', :platforms => :ruby
  gem 'guard-rspec', '2.1.1'
  gem 'uglifier', '1.0.3'
  gem 'jquery-rails'

end


